STR_CODIGO_SNIES = "CÓDIGO SNIES DEL PROGRAMA"
STR_PROGRAMA_ACADEMICO = "PROGRAMA ACADÉMICO"
STR_METODOLOGIA = "METODOLOGÍA"
STR_NOMBRE_IES = "INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)"
STR_TIPO_IES = "PRINCIPAL O SECCIONAL"
STR_DEPARTAMENTO = "DEPARTAMENTO DE DOMICILIO DE LA IES"
STR_MUNICIPIO = "MUNICIPIO DE DOMICILIO DE LA IES"
STR_NIVEL_FORMACION = "NIVEL DE FORMACIÓN"
STR_SEMESTRE = "SEMESTRE"
STR_ADMITIDOS = "ADMITIDOS"
STR_GRADUADOS = "GRADUADOS"
STR_INSCRITOS = "INSCRITOS"
STR_MATRICULADOS = "MATRICULADOS"
STR_PRIMER_CURSO = "PRIMER CURSO"
STR_GENERO = "SEXO"

COLUMNAS_RELEVANTES = [
    STR_CODIGO_SNIES,
    STR_PROGRAMA_ACADEMICO,
    STR_METODOLOGIA,
    STR_NOMBRE_IES,
    STR_TIPO_IES,
    STR_DEPARTAMENTO,
    STR_MUNICIPIO,
    STR_NIVEL_FORMACION,
    STR_SEMESTRE,
    STR_ADMITIDOS,
    STR_GRADUADOS,
    STR_INSCRITOS,
    STR_MATRICULADOS,
    STR_PRIMER_CURSO,
]

COLOR_MAP_MODALIDAD = {
    'Presencial': '#a8bded',
    'Virtual': '#c9eda8'
}

COLOR_MAP_SEXO = {
    'Femenino': '#a1074a',
    'Masculino': '#006745'
}

COLOR_MAP_NIVEL_FORMACION = {
    'Doctorado': '#f9917c',
    'Maestría': '#f0df7a',
    'Pregrado': '#a7f07a',
    'Especialización': '#7ad2f0'
}

COLORES_TENDENCIA = ['#6253a7', '#a253a7', '#189de8', '#30a063', '#a21656']

MAPEO_GENERO = {
    "Hombre": "Masculino",
    "Mujer": "Femenino",
    "Masculino": "Masculino",
    "Femenino": "Femenino",
    "No binario": "No binario"
}