STR_CODIGO_SNIES = "CÓDIGO SNIES DEL PROGRAMA"
STR_PROGRAMA_ACADEMICO = "PROGRAMA ACADÉMICO"
STR_METODOLOGIA = "METODOLOGÍA"
STR_NOMBRE_IES = "INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)"
STR_TIPO_IES = "PRINCIPAL O SECCIONAL"
STR_DEPARTAMENTO = "DEPARTAMENTO DE DOMICILIO DE LA IES"
STR_MUNICIPIO = "MUNICIPIO DE DOMICILIO DE LA IES"
STR_NIVEL_FORMACION = "NIVEL DE FORMACIÓN"
STR_SEMESTRE = "SEMESTRE"
STR_ADMITIDOS = "ADMITIDOS"
STR_GRADUADOS = "GRADUADOS"
STR_INSCRITOS = "INSCRITOS"
STR_MATRICULADOS = "MATRICULADOS"
STR_PRIMER_CURSO = "PRIMER CURSO"

COLUMNAS_RELEVANTES = [
    STR_CODIGO_SNIES,
    STR_PROGRAMA_ACADEMICO,
    STR_METODOLOGIA,
    STR_NOMBRE_IES,
    STR_TIPO_IES,
    STR_DEPARTAMENTO,
    STR_MUNICIPIO,
    STR_NIVEL_FORMACION,
    STR_SEMESTRE,
    STR_ADMITIDOS,
    STR_GRADUADOS,
    STR_INSCRITOS,
    STR_MATRICULADOS,
    STR_PRIMER_CURSO,
]